version: '3.8'

services:
  traefik:
    image: traefik:v3.3.6 # Or v2.11 if you prefer consistency with earlier examples
    container_name: traefik_prod # Corrected name
    restart: always
    command:
      # Core
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=WARN"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/traefik/letsencrypt:/letsencrypt"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M # Adjust based on monitoring
        reservations:
          memory: 128M
    labels:
      - "traefik.enable=true"

      # --- Dashboard Routing (Use ENV VAR for hostname) ---
      - "traefik.http.routers.traefik-dashboard-prod.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)"
      - "traefik.http.routers.traefik-dashboard-prod.entrypoints=websecure"
      - "traefik.http.routers.traefik-dashboard-prod.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-dashboard-prod.service=api@internal"
      - "traefik.http.routers.traefik-dashboard-prod.middlewares=admin-auth-prod@docker"
      - "traefik.http.middlewares.admin-auth-prod.basicauth.users=${TRAEFIK_AUTH_USERS}"

  # PostgreSQL Database
  db:
    build: ./database
    container_name: clogged_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Express TypeScript Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: clogged_server_prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ENDPOINT_SECRET_KEY: ${ENDPOINT_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5000/healthz || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    labels:
      - "traefik.enable=true" # Tell Traefik to expose this service
      - "traefik.http.routers.clogged-server-prod.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.clogged-server-prod.entrypoints=websecure"
      - "traefik.http.routers.clogged-server-prod.tls.certresolver=myresolver" # Use LE Cert
      # --- Service Definition ---
      - "traefik.http.services.clogged-server-prod-svc.loadbalancer.server.port=5000" # Internal PORT

  # Data Loader
  data-loader:
    build: ./dumper
    container_name: clogged_data_loader_prod
    restart: "no"
    profiles: ["tools"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: clogged_worker_prod
    restart: always
    command: [ "node", "dist/worker.js" ]
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    container_name: clogged_redis_prod
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local