version: '3.8'

services:
  db:
    build: ./database
    container_name: clogged_db_staging
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network-staging

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: clogged_server_staging
    restart: always
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ENDPOINT_SECRET_KEY: ${ENDPOINT_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5000/healthz || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network-staging

  data-loader:
    build: ./dumper
    container_name: clogged_data_loader_staging
    restart: "no"
    profiles: ["tools"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network-staging

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: clogged_worker_staging
    restart: always
    command: [ "node", "dist/worker.js" ]
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network-staging

  redis:
    image: redis:7.4-alpine
    container_name: clogged_redis_staging
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data_staging:/data
    networks:
      - app-network-staging

  cloudbeaver:
    image: dbeaver/cloudbeaver:25
    container_name: cloudbeaver_staging
    restart: always
    ports:
      - "8978:8978" # Map host port 8978 to container port 8978
    volumes:
      - cloudbeaver_data_staging:/opt/cloudbeaver/workspace # Persist workspace data
    depends_on:
      db:
        condition: service_healthy # Wait for the database to be ready
    networks:
      - app-network-staging # Connect to the same network as the db


networks:
  app-network-staging:
    driver: bridge

volumes:
  postgres_data_staging:
    driver: local
  nginx_logs_staging:
    driver: local
  redis_data_staging:
    driver: local
  cloudbeaver_data_staging: # Added volume for CloudBeaver
    driver: local