version: '3.8'

services:
  # PostgreSQL Database
  db:
    build: ./database
    container_name: clogged_db_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Express TypeScript Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: clogged_server_prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:5000/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    # deploy: # Optional resource limits
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 512M

  # React Client served by Nginx
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: clogged_client_prod
    restart: always
    networks:
      - app-network
    ports:
      - "5173:80"

  # Data Loader
  data-loader:
    build: ./dumper
    container_name: clogged_data_loader_prod
    restart: "no"
    profiles: ["tools"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: clogged_worker_prod
    restart: always
    command: [ "node", "dist/worker.js" ]
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:7.4-alpine
    container_name: clogged_redis_prod
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  nginx_logs:
    driver: local
  redis_data:
    driver: local