version: '3.8'

services:
  # PostgreSQL Database
  db:
    build: ./database
    container_name: clogged_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network-local

  # Express TypeScript Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: clogged_server
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      ENDPOINT_SECRET_KEY: ${ENDPOINT_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: npm run dev
    networks:
      - app-network-local

  data-loader:
    build: ./dumper
    container_name: clogged_data_loader
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network-local

  worker:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: clogged_worker
    restart: always
    command: npm run dev:worker
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${APP_DB_USER}
      DB_PASSWORD: ${APP_DB_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    networks:
      - app-network-local

  redis:
    image: redis:7.4-alpine
    container_name: clogged_redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - app-network-local

  # --- Logging Stack (Local Dev Version) ---

  loki:
    image: grafana/loki:3.4.1
    container_name: loki_local
    restart: always
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./logging/loki-config-local.yaml:/etc/loki/loki-config.yaml:ro
    networks:
      - app-network-local

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail_local
    restart: always
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logging/promtail-config-local.yaml:/etc/promtail/promtail-config.yaml:ro
    depends_on:
      - loki
    networks:
      - app-network-local

  grafana:
    image: grafana/grafana:11.6.1
    container_name: grafana_local
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./logging/grafana-datasources-staging.yaml:/etc/grafana/provisioning/datasources/loki-datasource.yaml:ro
    depends_on:
      - loki
    networks:
      - app-network-local


volumes:
  postgres_data:
  redis_data:

networks:
  app-network-local:
    driver: bridge