auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    s3:
      endpoint: ${B2_ENDPOINT_STAGING}
      region: ${B2_REGION_STAGING}
      bucketnames: ${B2_BUCKET_NAME_STAGING}
      access_key_id: ${B2_ACCESS_KEY_ID_STAGING}
      secret_access_key: ${B2_SECRET_ACCESS_KEY_STAGING}
      s3forcepathstyle: true
      insecure: false
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-05-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: s3

limits_config:
  retention_period: 168h # 7d * 24h = 168h

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false