# loki-config/loki-local-config.yaml

auth_enabled: false

target: all # Explicitly set monolithic mode

server:
  http_listen_port: 3100
  grpc_listen_port: 9096 # Define standard gRPC port

common:
  instance_addr: 127.0.0.1 # Keep localhost address
  path_prefix: /loki       # Directory within the volume for data
  storage:
    filesystem: # Using filesystem storage
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1 # Fine for single instance
  ring:
    # For 'inmemory', only the store type is strictly needed
    kvstore:
      store: inmemory

limits_config:
  allow_structured_metadata: false # Keep the previous fix

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper # Using older shipper for simplicity with filesystem
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Optional: Define ruler if you plan on using alerting rules
# ruler:
#   alertmanager_url: http://localhost:9093 # Example