name: Deploy Clogged App

on:
  push:
    branches:
      - main     # Trigger on push to main (for production)
      - staging  # Trigger on push to staging

jobs:
  deploy:
    # Job name is dynamic based on the branch
    name: Deploy to ${{ github.ref_name == 'main' && 'Production' || 'Staging' }}
    runs-on: ubuntu-latest

    # Select the GitHub Environment based on the branch triggering the workflow
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      # url: Optional: Can set a URL based on the environment for deployment status checks

    steps:
      - name: Setup DigitalOcean firewall
        uses: earthpyy/setup-digitalocean-firewall@v1.0.1
        with:
          access-token: ${{ secrets.DO_ACCESS_TOKEN }}
          firewall-id: ${{ secrets.DO_FIREWALL_ID }}

      - name: Checkout code
        uses: actions/checkout@v4
        # Ensure full history is fetched if needed by deploy script (usually not needed for reset --hard)
        # with:
        #   fetch-depth: 0

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.2 # Or latest version
        with:
          # These secrets are now automatically sourced from the selected GitHub Environment
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Pass environment-specific info and branch name to the deploy script
          script: |
            export DEPLOY_BRANCH=${{ github.ref_name }}
            export COMPOSE_FILE_NAME=${{ vars.COMPOSE_FILE_NAME }} # Read variable from Environment
            export APP_DEPLOY_PATH=${{ vars.DEPLOY_PATH }}         # Read variable from Environment
            
            echo "Executing deployment script on $host for branch $DEPLOY_BRANCH"
            cd $APP_DEPLOY_PATH
            ./deploy.sh # Execute the deployment script